name: Server Tests

on:
  push:
    branches: [main, app, preprod]
  pull_request:
    branches: [main, app, preprod]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
      
      redis-cache:
        image: redis:6.2-alpine
        ports:
          - 6379:6379
      redis-queue:
        image: redis:6.2-alpine
        ports:
          - 6380:6379

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}

      - name: Install Bench
        run: pip install frappe-bench

      - name: Init Bench
        run: |
          # --skip-assets permet de gagner bcp de temps en CI
          bench init frappe-bench --skip-redis-config-generation --frappe-branch version-15 --python python3.11 --skip-assets
          cd frappe-bench
          bench set-config -g redis_cache redis://localhost:6379
          bench set-config -g redis_queue redis://localhost:6380

      - name: Get Apps
        run: |
          cd frappe-bench
          bench get-app --branch version-15 erpnext
          bench get-app lodin ${{ github.workspace }}

      - name: Setup Site
        run: |
          cd frappe-bench
          # Remplacement de --no-mariadb-socket par la nouvelle norme de scope
          bench new-site lodin.localhost \
            --db-host 127.0.0.1 \
            --mariadb-root-password root \
            --admin-password admin \
            --mariadb-user-host-login-scope='%'
          
          # Ordre crucial : ERPNext d'abord, Lodin ensuite
          bench --site lodin.localhost install-app erpnext
          bench --site lodin.localhost install-app lodin

      - name: Run Tests
        run: |
          cd frappe-bench
          bench --site lodin.localhost run-tests --app lodin