name: Linters

on:
  push:
    branches: [main, app, preprod]
  pull_request:
    branches: [main, app, preprod]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Clone Frappe Semgrep Rules
        run: git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules

      - name: Run Semgrep
        run: semgrep --config ./frappe-semgrep-rules/rules --config r/python.lang.correctness --error .

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .
